[package]
name = "paidtype2"
version = "0.1.0"
edition = "2024"

[lib]
name = "freetype"
path = "src/lib.rs"

[[example]]
name = "initializing"
path = "examples/intializing.rs"

[dependencies]

[build-dependencies]
cmake = "0.1"
